services:
  web:
    build: .
    command: gunicorn dadoconcreto_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=dadoconcreto_api.settings
      - PYTHONPATH=/app
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
