services:
  web:
      # Build the image from the Dockerfile in the current directory
    build: .
    # Host the app on port 8000
    ports:
      - 9090:9090
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
